[package]
name = "ProboscideaVolcanium"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "proboscidea_volcanium"
path = "ProboscideaVolcanium.rs"

[dependencies]
itertools = "0.10.5"
regex = "1.7.1"
